### ISSUE TITLE
crash for Moonshae Pixie & Myrkul's Edict

### ISSUE THREAD

**Issue by kevlahnota** [Card-Forge/forge#1068]
crash with #1048

log:

```
EDT > java.lang.RuntimeException: crash in raw Ability, check card script of Myrkul's Edict
    at forge.game.card.CardFactoryUtil.addAbilityFactoryAbilities(CardFactoryUtil.java:608)
    at forge.game.card.CardFactory.readCardFace(CardFactory.java:450)
    at forge.game.card.CardFactory.readCard(CardFactory.java:361)
    at forge.game.card.CardFactory.getCard(CardFactory.java:246)
    at forge.game.card.CardFactory.getCard(CardFactory.java:242)
    at forge.game.card.Card.fromPaperCard(Card.java:6532)
    at forge.game.card.Card.getCardForUi(Card.java:6543)
    at forge.game.card.CardView.getCardForUi(CardView.java:64)
    at forge.card.CardRenderer.drawCard(CardRenderer.java:603)
    at forge.itemmanager.views.ImageView$ItemInfo.draw(ImageView.java:991)
    at forge.itemmanager.views.ImageView$Pile.draw(ImageView.java:920)
    at forge.itemmanager.views.ImageView$Group.draw(ImageView.java:829)
    at forge.Graphics.draw(Graphics.java:176)
    at forge.toolbox.FContainer.draw(FContainer.java:64)
    at forge.toolbox.FScrollPane.draw(FScrollPane.java:332)
    at forge.Graphics.draw(Graphics.java:176)
    at forge.toolbox.FContainer.draw(FContainer.java:64)
    at forge.Graphics.draw(Graphics.java:176)
    at forge.toolbox.FContainer.draw(FContainer.java:64)
    at forge.Graphics.draw(Graphics.java:176)
    at forge.toolbox.FContainer.draw(FContainer.java:64)
    at forge.screens.FScreen.draw(FScreen.java:164)
    at forge.Forge.render(Forge.java:887)
    at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Window.update(Lwjgl3Window.java:387)
    at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.loop(Lwjgl3Application.java:192)
    at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.<init>(Lwjgl3Application.java:166)
    at forge.app.Main.main(Main.java:148)
```

and

```
EDT > java.lang.RuntimeException: Error in Trigger for Card: Moonshae Pixie
    at forge.game.trigger.TriggerHandler.parseTrigger(TriggerHandler.java:141)
    at forge.game.card.CardFactory.readCardFace(CardFactory.java:409)
    at forge.game.card.CardFactory.readCard(CardFactory.java:361)
    at forge.game.card.CardFactory.getCard(CardFactory.java:246)
    at forge.game.card.CardFactory.getCard(CardFactory.java:242)
    at forge.game.card.Card.fromPaperCard(Card.java:6532)
    at forge.game.card.Card.getCardForUi(Card.java:6543)
    at forge.game.card.CardView.getCardForUi(CardView.java:64)
    at forge.card.CardRenderer.drawCard(CardRenderer.java:603)
    at forge.itemmanager.views.ImageView$ItemInfo.draw(ImageView.java:991)
    at forge.itemmanager.views.ImageView$Pile.draw(ImageView.java:920)
    at forge.itemmanager.views.ImageView$Group.draw(ImageView.java:829)
    at forge.Graphics.draw(Graphics.java:176)
    at forge.toolbox.FContainer.draw(FContainer.java:64)
    at forge.toolbox.FScrollPane.draw(FScrollPane.java:332)
    at forge.Graphics.draw(Graphics.java:176)
    at forge.toolbox.FContainer.draw(FContainer.java:64)
    at forge.Graphics.draw(Graphics.java:176)
    at forge.toolbox.FContainer.draw(FContainer.java:64)
    at forge.Graphics.draw(Graphics.java:176)
    at forge.toolbox.FContainer.draw(FContainer.java:64)
    at forge.screens.FScreen.draw(FScreen.java:164)
    at forge.Forge.render(Forge.java:887)
    at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Window.update(Lwjgl3Window.java:387)
    at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.loop(Lwjgl3Application.java:192)
    at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.<init>(Lwjgl3Application.java:166)
    at forge.app.Main.main(Main.java:148)
```

**Comment by kevlahnota** [comment]
just tried to open deck editor, type Myrkul's Edict, after hitting enter, crashes... 
```
EDT > java.lang.RuntimeException: crash in raw Ability, check card script of Myrkul's Edict
	at forge.game.card.CardFactoryUtil.addAbilityFactoryAbilities(CardFactoryUtil.java:608)
	at forge.game.card.CardFactory.readCardFace(CardFactory.java:450)
	at forge.game.card.CardFactory.readCard(CardFactory.java:361)
	at forge.game.card.CardFactory.getCard(CardFactory.java:246)
	at forge.game.card.CardFactory.getCard(CardFactory.java:242)
	at forge.game.card.Card.fromPaperCard(Card.java:6532)
	at forge.game.card.Card.getCardForUi(Card.java:6543)
	at forge.game.card.CardView.getCardForUi(CardView.java:64)
	at forge.card.CardRenderer.drawCard(CardRenderer.java:606)
	at forge.itemmanager.views.ImageView$ItemInfo.draw(ImageView.java:991)
	at forge.itemmanager.views.ImageView$Pile.draw(ImageView.java:920)
	at forge.itemmanager.views.ImageView$Group.draw(ImageView.java:829)
	at forge.Graphics.draw(Graphics.java:176)
	at forge.toolbox.FContainer.draw(FContainer.java:64)
	at forge.toolbox.FScrollPane.draw(FScrollPane.java:332)
	at forge.Graphics.draw(Graphics.java:176)
	at forge.toolbox.FContainer.draw(FContainer.java:64)
	at forge.Graphics.draw(Graphics.java:176)
	at forge.toolbox.FContainer.draw(FContainer.java:64)
	at forge.Graphics.draw(Graphics.java:176)
	at forge.toolbox.FContainer.draw(FContainer.java:64)
	at forge.screens.FScreen.draw(FScreen.java:164)
	at forge.Forge.render(Forge.java:887)
	at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Window.update(Lwjgl3Window.java:387)
	at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.loop(Lwjgl3Application.java:192)
	at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.<init>(Lwjgl3Application.java:166)
	at forge.app.Main.main(Main.java:148)
Caused by: java.lang.RuntimeException: AbilityFactory:getAbility: crash when trying to create ability  of card: Myrkul's Edict
	at forge.game.ability.AbilityFactory.getAbility(AbilityFactory.java:157)
	at forge.game.ability.AbilityFactory.getAbility(AbilityFactory.java:116)
	at forge.game.ability.AbilityFactory.getAbility(AbilityFactory.java:113)
	at forge.game.card.CardFactoryUtil.addAbilityFactoryAbilities(CardFactoryUtil.java:595)
	... 26 more
Caused by: java.lang.RuntimeException: AbilityFactory : getAbility -- no API in Myrkul's Edict: ChoosePlayer | Defined$ You | Choices$ Player.Opponent | SubAbility$ DBSac | StackDescription$ SpellDescription | SpellDescription$ 1—9 VERT Choose an opponent. That player sacrifices a creature.
	at forge.game.ability.AbilityFactory.getAbility(AbilityFactory.java:145)
	at forge.game.ability.AbilityFactory.getAbility(AbilityFactory.java:174)
	at forge.game.ability.AbilityFactory.getSubAbility(AbilityFactory.java:457)
	at forge.game.ability.AbilityFactory.getAbility(AbilityFactory.java:299)
	at forge.game.ability.AbilityFactory.getAbility(AbilityFactory.java:179)
	at forge.game.ability.AbilityFactory.getAbility(AbilityFactory.java:148)
	... 29 more
```

**Comment by Hanmac** [comment]
> just tried to open deck editor, type Myrkul's Edict, after hitting enter, crashes...
> 
> ```
> EDT > java.lang.RuntimeException: crash in raw Ability, check card script of Myrkul's Edict
> 	at forge.game.card.CardFactoryUtil.addAbilityFactoryAbilities(CardFactoryUtil.java:608)
> 	at forge.game.card.CardFactory.readCardFace(CardFactory.java:450)
> 	at forge.game.card.CardFactory.readCard(CardFactory.java:361)
> 	at forge.game.card.CardFactory.getCard(CardFactory.java:246)
> 	at forge.game.card.CardFactory.getCard(CardFactory.java:242)
> 	at forge.game.card.Card.fromPaperCard(Card.java:6532)
> 	at forge.game.card.Card.getCardForUi(Card.java:6543)
> 	at forge.game.card.CardView.getCardForUi(CardView.java:64)
> 	at forge.card.CardRenderer.drawCard(CardRenderer.java:606)
> 	at forge.itemmanager.views.ImageView$ItemInfo.draw(ImageView.java:991)
> 	at forge.itemmanager.views.ImageView$Pile.draw(ImageView.java:920)
> 	at forge.itemmanager.views.ImageView$Group.draw(ImageView.java:829)
> 	at forge.Graphics.draw(Graphics.java:176)
> 	at forge.toolbox.FContainer.draw(FContainer.java:64)
> 	at forge.toolbox.FScrollPane.draw(FScrollPane.java:332)
> 	at forge.Graphics.draw(Graphics.java:176)
> 	at forge.toolbox.FContainer.draw(FContainer.java:64)
> 	at forge.Graphics.draw(Graphics.java:176)
> 	at forge.toolbox.FContainer.draw(FContainer.java:64)
> 	at forge.Graphics.draw(Graphics.java:176)
> 	at forge.toolbox.FContainer.draw(FContainer.java:64)
> 	at forge.screens.FScreen.draw(FScreen.java:164)
> 	at forge.Forge.render(Forge.java:887)
> 	at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Window.update(Lwjgl3Window.java:387)
> 	at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.loop(Lwjgl3Application.java:192)
> 	at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.<init>(Lwjgl3Application.java:166)
> 	at forge.app.Main.main(Main.java:148)
> Caused by: java.lang.RuntimeException: AbilityFactory:getAbility: crash when trying to create ability  of card: Myrkul's Edict
> 	at forge.game.ability.AbilityFactory.getAbility(AbilityFactory.java:157)
> 	at forge.game.ability.AbilityFactory.getAbility(AbilityFactory.java:116)
> 	at forge.game.ability.AbilityFactory.getAbility(AbilityFactory.java:113)
> 	at forge.game.card.CardFactoryUtil.addAbilityFactoryAbilities(CardFactoryUtil.java:595)
> 	... 26 more
> Caused by: java.lang.RuntimeException: AbilityFactory : getAbility -- no API in Myrkul's Edict: ChoosePlayer | Defined$ You | Choices$ Player.Opponent | SubAbility$ DBSac | StackDescription$ SpellDescription | SpellDescription$ 1—9 VERT Choose an opponent. That player sacrifices a creature.
> 	at forge.game.ability.AbilityFactory.getAbility(AbilityFactory.java:145)
> 	at forge.game.ability.AbilityFactory.getAbility(AbilityFactory.java:174)
> 	at forge.game.ability.AbilityFactory.getSubAbility(AbilityFactory.java:457)
> 	at forge.game.ability.AbilityFactory.getAbility(AbilityFactory.java:299)
> 	at forge.game.ability.AbilityFactory.getAbility(AbilityFactory.java:179)
> 	at forge.game.ability.AbilityFactory.getAbility(AbilityFactory.java:148)
> 	... 29 more
> ```

`SVar:OneOppSac:ChoosePlayer `   it misses `DB$ `

**Comment by squee1968** [comment]
Thanks for your help, everyone
