### ISSUE TITLE
Cannot launch for first time on Linux: java.lang.ExceptionInInitializerError

### ISSUE THREAD

**Issue by everettttt** [Card-Forge/forge#1196]
**Describe the bug**

I try launching Forge for the first time but can't. See below for the full error output and my system specs.

**To Reproduce**

1. Download [forge-gui-desktop-1.6.9.tar.bz2](https://releases.cardforge.org/forge/forge-gui-desktop/1.6.9/forge-gui-desktop-1.6.9.tar.bz2) and extract to `~/Games/forge/`.
2. Double-click `forge-gui-desktop-1.6.9-jar-with-dependencies.jar`.
3. See the forge logo. After it tries "Opening main window..." I get an error:

```
Description: [describe what you were doing when the crash occurred]

[spoiler=ExceptionInInitializerError][code]
Forge Version:    1.6.9-r-1u
Operating System: Linux 5.18.14-arch1-1 amd64
Java Version:     18.0.2 N/A

java.lang.ExceptionInInitializerError
	at com.thoughtworks.xstream.XStream.setupConverters(XStream.java:807)
	at com.thoughtworks.xstream.XStream.<init>(XStream.java:574)
	at com.thoughtworks.xstream.XStream.<init>(XStream.java:496)
	at com.thoughtworks.xstream.XStream.<init>(XStream.java:465)
	at com.thoughtworks.xstream.XStream.<init>(XStream.java:411)
	at com.thoughtworks.xstream.XStream.<init>(XStream.java:350)
	at forge.util.IgnoringXStream.<init>(IgnoringXStream.java:18)
	at forge.quest.bazaar.QuestBazaarManager.load(QuestBazaarManager.java:71)
	at forge.quest.bazaar.QuestBazaarManager.getStallNames(QuestBazaarManager.java:191)
	at forge.screens.bazaar.VBazaarUI.populateStalls(VBazaarUI.java:42)
	at forge.screens.bazaar.CBazaarUI.initBazaar(CBazaarUI.java:26)
	at forge.screens.bazaar.VBazaarUI.instantiate(VBazaarUI.java:103)
	at forge.view.FView.cacheUIStates(FView.java:519)
	at forge.view.FView.initialize(FView.java:115)
	at forge.control.FControl$3.run(FControl.java:262)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:318)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:773)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:720)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:714)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:742)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
Caused by: java.lang.reflect.InaccessibleObjectException: Unable to make field private final java.util.Comparator java.util.TreeMap.comparator accessible: module java.base does not "opens java.util" to unnamed module @cd3fee8
	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:354)
	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:297)
	at java.base/java.lang.reflect.Field.checkCanSetAccessible(Field.java:180)
	at java.base/java.lang.reflect.Field.setAccessible(Field.java:174)
	at com.thoughtworks.xstream.core.util.Fields.locate(Fields.java:39)
	at com.thoughtworks.xstream.converters.collections.TreeMapConverter.<clinit>(TreeMapConverter.java:50)
	... 28 more
[/code][/spoiler]
```

**Screenshots**

![image](https://user-images.githubusercontent.com/9023041/180850882-5124a336-590e-491d-94e7-3868c10a2540.png)

**Desktop (please complete the following information):**
 - OS: EndeavourOS
 - Version: 2021.12.17

**Additional context**

Output of `java -version`:

```
openjdk version "18.0.2" 2022-07-19
OpenJDK Runtime Environment (build 18.0.2+9)
OpenJDK 64-Bit Server VM (build 18.0.2+9, mixed mode)
```

**Comment by kevlahnota** [comment]
try to download latest 1.6.53 release or 1.6.54.SNAPSHOT and run forge.sh, you're trying to run a very old build (which doesn't grant access that java 11 and above version needs...)

**Comment by everettttt** [comment]
Oh... 1.6.53 > 1.6.9 in this system. I downloaded the 1.6.9 zip and ran `bash forge.sh` and it worked. Closing.
