### ISSUE TITLE
creature type select broken again.

### ISSUE THREAD

**Issue by corwin72** [Card-Forge/forge#2144]
**Describe the bug**
I think that the token creature type list is broken again
 
**To Reproduce**
Play a card that you select a creature type.

**Expected behavior**
Be able to select an available creature type from the list.

**Screenshots**
No specified file for 'w_2_2_astartes_warrior_vigilance_40k.jpg'.. Attempting to download from default Url
Game-9 > java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
        at java.util.LinkedList.checkElementIndex(LinkedList.java:555)
        at java.util.LinkedList.get(LinkedList.java:476)
        at forge.util.collect.FCollection.get(FCollection.java:396)
        at forge.game.ability.AbilityUtils.calculateAmount(AbilityUtils.java:691)
        at forge.game.ability.AbilityUtils.calculateAmount(AbilityUtils.java:418)
        at forge.game.card.token.TokenInfo.getProtoType(TokenInfo.java:287)
        at forge.game.card.token.TokenInfo.getProtoType(TokenInfo.java:266)
        at forge.player.PlayerControllerHuman.sortCreatureTypes(PlayerControllerHuman.java:1332)
        at forge.player.PlayerControllerHuman.chooseSomeType(PlayerControllerHuman.java:1260)
        at forge.game.player.PlayerController.chooseSomeType(PlayerController.java:184)
        at forge.game.ability.effects.ChooseTypeEffect.resolve(ChooseTypeEffect.java:114)
        at forge.game.spellability.AbilitySub.resolve(AbilitySub.java:105)
        at forge.game.ability.AbilityUtils.resolveApiAbility(AbilityUtils.java:1428)
        at forge.game.ability.AbilityUtils.resolve(AbilityUtils.java:1400)
        at forge.player.HumanPlaySpellAbility.playAbility(HumanPlaySpellAbility.java:194)
        at forge.player.HumanPlay.playSpellAbilityNoStack(HumanPlay.java:198)
        at forge.player.PlayerControllerHuman.playSpellAbilityNoStack(PlayerControllerHuman.java:305)
        at forge.game.replacement.ReplacementHandler.executeReplacement(ReplacementHandler.java:419)
        at forge.game.replacement.ReplacementHandler.run(ReplacementHandler.java:277)
        at forge.game.replacement.ReplacementHandler.run(ReplacementHandler.java:253)
        at forge.game.GameAction.changeZone(GameAction.java:359)
        at forge.game.GameAction.moveTo(GameAction.java:791)
        at forge.game.GameAction.moveTo(GameAction.java:750)
        at forge.game.GameAction.moveToPlay(GameAction.java:894)
        at forge.game.ability.effects.PermanentEffect.resolve(PermanentEffect.java:40)
        at forge.game.ability.SpellApiBased.resolve(SpellApiBased.java:51)
        at forge.game.ability.AbilityUtils.resolveApiAbility(AbilityUtils.java:1428)
        at forge.game.ability.AbilityUtils.resolve(AbilityUtils.java:1400)
        at forge.game.zone.MagicStack.resolveStack(MagicStack.java:527)
        at forge.game.phase.PhaseHandler.startFirstTurn(PhaseHandler.java:1124)
        at forge.game.GameAction.startGame(GameAction.java:2095)
        at forge.game.Match.startGame(Match.java:90)
        at forge.gamemodes.match.HostedMatch$2.run(HostedMatch.java:262)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)

From the Dec18th snapshot forge-gui-desktop-1.6.54.1218x.SNAPSHOT.tar.bz2

**Comment by corwin72** [comment]
I am showing this still broken as of todays snapshot:
From Bloodline pretender

SVar 'CostCountersRemoved' not found in ability, fallback to Card (Relic Amulet). Ability is ({2}, {T}, Remove all charge counters from Relic Amulet: It deals that much damage to target creature.)
Game-0 > java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
        at java.util.LinkedList.checkElementIndex(LinkedList.java:555)
        at java.util.LinkedList.get(LinkedList.java:476)
        at forge.util.collect.FCollection.get(FCollection.java:396)
        at forge.game.ability.AbilityUtils.calculateAmount(AbilityUtils.java:691)
        at forge.game.ability.AbilityUtils.calculateAmount(AbilityUtils.java:418)
        at forge.game.card.token.TokenInfo.getProtoType(TokenInfo.java:287)
        at forge.game.card.token.TokenInfo.getProtoType(TokenInfo.java:266)
        at forge.player.PlayerControllerHuman.sortCreatureTypes(PlayerControllerHuman.java:1332)
        at forge.player.PlayerControllerHuman.chooseSomeType(PlayerControllerHuman.java:1260)
        at forge.game.player.PlayerController.chooseSomeType(PlayerController.java:184)
        at forge.game.ability.effects.ChooseTypeEffect.resolve(ChooseTypeEffect.java:114)
        at forge.game.spellability.AbilitySub.resolve(AbilitySub.java:105)
        at forge.game.ability.AbilityUtils.resolveApiAbility(AbilityUtils.java:1428)
        at forge.game.ability.AbilityUtils.resolve(AbilityUtils.java:1400)
        at forge.player.HumanPlaySpellAbility.playAbility(HumanPlaySpellAbility.java:197)
        at forge.player.HumanPlay.playSpellAbilityNoStack(HumanPlay.java:198)
        at forge.player.PlayerControllerHuman.playSpellAbilityNoStack(PlayerControllerHuman.java:305)
        at forge.game.replacement.ReplacementHandler.executeReplacement(ReplacementHandler.java:419)
        at forge.game.replacement.ReplacementHandler.run(ReplacementHandler.java:277)
        at forge.game.replacement.ReplacementHandler.run(ReplacementHandler.java:253)
        at forge.game.GameAction.changeZone(GameAction.java:359)
        at forge.game.GameAction.moveTo(GameAction.java:791)
        at forge.game.GameAction.moveTo(GameAction.java:750)
        at forge.game.GameAction.moveToPlay(GameAction.java:894)
        at forge.game.ability.effects.PermanentEffect.resolve(PermanentEffect.java:40)
        at forge.game.ability.SpellApiBased.resolve(SpellApiBased.java:51)
        at forge.game.ability.AbilityUtils.resolveApiAbility(AbilityUtils.java:1428)
        at forge.game.ability.AbilityUtils.resolve(AbilityUtils.java:1400)
        at forge.game.zone.MagicStack.resolveStack(MagicStack.java:527)
        at forge.game.phase.PhaseHandler.startFirstTurn(PhaseHandler.java:1124)
        at forge.game.GameAction.startGame(GameAction.java:2095)
        at forge.game.Match.startGame(Match.java:90)
        at forge.gamemodes.match.HostedMatch$2.run(HostedMatch.java:262)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)

1.6.54.1220.snapshot
