### ISSUE TITLE
Error on launch on Mac M1

### ISSUE THREAD

**Issue by DavidTortolo** [Card-Forge/forge#2856]
Im using Forge 1.6.9 and I have a Mac M1 and when I run forge.command I get this error:

```
java.lang.ExceptionInInitializerError
	at com.thoughtworks.xstream.XStream.setupConverters(XStream.java:807)
	at com.thoughtworks.xstream.XStream.<init>(XStream.java:574)
	at com.thoughtworks.xstream.XStream.<init>(XStream.java:496)
	at com.thoughtworks.xstream.XStream.<init>(XStream.java:465)
	at com.thoughtworks.xstream.XStream.<init>(XStream.java:411)
	at com.thoughtworks.xstream.XStream.<init>(XStream.java:350)
	at forge.util.IgnoringXStream.<init>(IgnoringXStream.java:18)
	at forge.quest.bazaar.QuestBazaarManager.load(QuestBazaarManager.java:71)
	at forge.quest.bazaar.QuestBazaarManager.getStallNames(QuestBazaarManager.java:191)
	at forge.screens.bazaar.VBazaarUI.populateStalls(VBazaarUI.java:42)
	at forge.screens.bazaar.CBazaarUI.initBazaar(CBazaarUI.java:26)
	at forge.screens.bazaar.VBazaarUI.instantiate(VBazaarUI.java:103)
	at forge.view.FView.cacheUIStates(FView.java:519)
	at forge.view.FView.initialize(FView.java:115)
	at forge.control.FControl$3.run(FControl.java:262)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:318)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:773)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:720)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:714)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:742)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
Caused by: java.lang.reflect.InaccessibleObjectException: Unable to make field private final java.util.Comparator java.util.TreeMap.comparator accessible: module java.base does not "opens java.util" to unnamed module @5a65309b
	at java.base/java.lang.reflect.AccessibleObject.throwInaccessibleObjectException(AccessibleObject.java:387)
	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:363)
	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:311)
	at java.base/java.lang.reflect.Field.checkCanSetAccessible(Field.java:180)
	at java.base/java.lang.reflect.Field.setAccessible(Field.java:174)
	at com.thoughtworks.xstream.core.util.Fields.locate(Fields.java:39)
	at com.thoughtworks.xstream.converters.collections.TreeMapConverter.<clinit>(TreeMapConverter.java:50)
	... 28 more
```

NOTE: I tried to run the script from a terminal with Rosetta and got the same issue.

**Comment by tool4ever** [comment]
That version is 5 years old...
Use a newer and check Wiki for guidance
