### ISSUE TITLE
NPE when AI tries to decide attackers if it could attack a battle

### ISSUE THREAD

**Issue by PaulHofma** [Card-Forge/forge#3034]
Forge version: 1.6.56
OS: Mac OS Ventura 13.3.1 (apple M2)
Java: OpenJDK 11.0.16.1
Stacktrace:
`Game-3 > java.lang.NullPointerException
	at forge.ai.AiAttackController.declareAttackers(AiAttackController.java:754)
	at forge.ai.AiController.getPredictedCombat(AiController.java:140)
	at forge.ai.ComputerUtilCard.doesCreatureAttackAI(ComputerUtilCard.java:619)
	at forge.ai.ComputerUtil.castPermanentInMain1(ComputerUtil.java:1080)
	at forge.ai.ability.PermanentAi.checkPhaseRestrictions(PermanentAi.java:43)
	at forge.ai.ability.PermanentCreatureAi.checkPhaseRestrictions(PermanentCreatureAi.java:114)
	at forge.ai.SpellAbilityAi.canPlayWithoutRestrict(SpellAbilityAi.java:84)
	at forge.ai.SpellAbilityAi.canPlayAI(SpellAbilityAi.java:54)
	at forge.ai.SpellAbilityAi.canPlayAIWithSubs(SpellAbilityAi.java:37)
	at forge.ai.AiController.canPlaySa(AiController.java:892)
	at forge.ai.AiController.canPlayAndPayForFace(AiController.java:804)
	at forge.ai.AiController.canPlayAndPayFor(AiController.java:754)
	at forge.ai.AiController.chooseSpellAbilityToPlayFromList(AiController.java:1770)
	at forge.ai.AiController.getSpellAbilityToPlay(AiController.java:1726)
	at forge.ai.AiController.chooseSpellAbilityToPlay(AiController.java:1556)
	at forge.ai.PlayerControllerAi.chooseSpellAbilityToPlay(PlayerControllerAi.java:662)
	at forge.game.phase.PhaseHandler.startFirstTurn(PhaseHandler.java:1033)
	at forge.game.GameAction.startGame(GameAction.java:2088)
	at forge.game.Match.startGame(Match.java:90)
	at forge.gamemodes.match.HostedMatch$2.run(HostedMatch.java:255)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)`

So to reiterate the title: whenever an opposing AI plays a battle and then goes to the combat phase (I have not double checked whether it's beginning of combat or declare attacks, but I'm going to guess declare attacks), the game (hard) crashes with a Nullpointer Exception. I've observed this every single time an opponent played a battle, and then moved to the declare attackers step, so it appears to be a general thing, not related to (for example) a specific battle. Please let me know if there's additional info that might be helpful.

**Comment by tool4ever** [comment]
Fixed by #3018
