### ISSUE TITLE
AI: Progressive slowdown when running complex predictions in a stalled battlefield state

### ISSUE THREAD

**Issue by schnautzr** [Card-Forge/forge#3410]
When Endless Swarm is in play, there is a risk of the game slowing to a standstill the longer it remains in play. The AI appears to be considering whether to activate mana abilities at times when there is nothing to pay for.

![image](https://github.com/Card-Forge/forge/assets/10385459/d312edc0-c108-4d18-8cd8-2537ebde7c8c)

**Comment by schnautzr** [comment]
@Agetian

**Comment by Agetian** [comment]
I'll definitely take a look at this one soon, I'll see what I can do.
This is definitely not specific to Endless Swarm in particular, you will see similar behavior with lots of token decks since at a certain threshold (dependent, of course, on the player's PC specs, especially RAM, but also CPU speed), the game will progressively start slowing down and will eventually grind down to a halt (or become unplayably bad). I've seen this sort of behavior with token decks revolving around multiple doublers such as Doubling Season and lots of token generators. The unfortunate thing is, the AI in its current design sort of has to run many checks for every single card object present on the battlefield. What seems obvious to the human player ("hey, the AI can't do anything here, what could it possibly be thinking about?") may not be so obvious for the AI algorithm which has to run checks for static abilities, presence of activated abilities that may be possible to activate, some predictions for combat, and many other things, some of which involve going over the entire battlefield and examining every card object. That said, there is, of course, room for optimization here, and I'll see what exactly is taking the AI so long in this particular case :) If I find any room for improvement, I'll handle it :)

At any rate, definitely not the case for an AI flag here - if we follow this logic, we would eventually come to a conclusion that we simply need to ban any form of token generation for the AI at all :D

Do you have a battlefield state where the AI is already slow for you? I might run a profiler to determine what's going on exactly.

**Comment by schnautzr** [comment]
No, but I did take a screenshot:

![image](https://github.com/Card-Forge/forge/assets/10385459/ce597dd4-9400-42d2-80ee-22c55d13f449)

**Comment by Agetian** [comment]
Alright, I'll see if I can reproduce it from that state :)
Can you check if this game state is slow for you? This runs adequately normal for me, with no slowdown. If it won't be slow for you either, it'll indicate that what you're experiencing is a more complex interaction than just having an Endless Swarm out and/or the presence of Elderscale Wurm on the human side. 

[ai_endless_swarm.txt](https://github.com/Card-Forge/forge/files/11953865/ai_endless_swarm.txt)

**Comment by schnautzr** [comment]
Seems reasonably fast.

**Comment by Agetian** [comment]
Alright, so here's some investigation on what's going on here. First off, here's a game state where the AI will definitely be slow even on a very fast machine with lots of RAM (on my machine, the next AI's declare attack phase will take over half a minute)
[ai_slowdown.txt](https://github.com/Card-Forge/forge/files/11969723/ai_slowdown.txt)

The slowdown only happens if the AI is unable to perform an assault attack (or possibly attritional attack), which leads it to initiate a more careful evaluation of what should and what shouldn't attack. In this particular board state, Elderscale Wurm is preventing combat damage since the player is at exactly 7 life. However, this isn't the only reason why this may happen - in practically any event where the AI is unable to decide on an assault, it'll go into "evaluation mode", trying various combinations of attackers and blockers and then evaluating damage reduction to see if anything at all is going to work. Obviously, this takes longer and longer the more card objects there are on the battlefield (and it looks like the increase in evaluation time is not linear, every new card object adds more time to the evaluation than the previous one, most likely due to the fact that the number of possible attacker/blocker permutations becomes significantly higher as well).

Here's the stack trace dump of what's going on while the AI is taking its time in the Declare Attackers phase to consider things:
"Game-0@6011" prio=6 tid=0x39 nid=NA runnable
  java.lang.Thread.State: RUNNABLE
	  at forge.game.card.Card.updateReplacementEffects(Card.java:6388)
	  at forge.game.card.CardState.getReplacementEffects(CardState.java:481)
	  at forge.game.card.Card.getReplacementEffects(Card.java:6374)
	  at forge.game.replacement.ReplacementHandler$3.visit(ReplacementHandler.java:950)
	  at forge.game.replacement.ReplacementHandler$3.visit(ReplacementHandler.java:947)
	  at forge.util.Visitor.visitAll(Visitor.java:16)
	  at forge.game.Game.forEachCardInGame(Game.java:675)
	  at forge.game.replacement.ReplacementHandler.isPreventCombatDamageThisTurn(ReplacementHandler.java:947)
	  at forge.game.GameEntity.staticDamagePrevention(GameEntity.java:86)
	  **at forge.ai.ComputerUtilCombat.predictDamageTo(ComputerUtilCombat.java:2242)
	  at forge.ai.ComputerUtilCombat.predictDamageTo(ComputerUtilCombat.java:2218)
	  at forge.ai.ComputerUtilCombat.predictDamageByBlockerWithoutDoubleStrike(ComputerUtilCombat.java:621)
	  at forge.ai.ComputerUtilCombat.dealsDamageAsBlocker(ComputerUtilCombat.java:575)
	  at forge.ai.AiBlockController.makeGangBlocks(AiBlockController.java:530)
	  at forge.ai.AiBlockController.assignBlockers(AiBlockController.java:1115)
	  at forge.ai.AiBlockController.assignBlockersForCombat(AiBlockController.java:1045)
	  at forge.ai.ComputerUtil.predictNextCombatsRemainingLife(ComputerUtil.java:3217)
	  at forge.ai.AiAttackController.notNeededAsBlockers(AiAttackController.java:444)
	  at forge.ai.AiAttackController.declareAttackers(AiAttackController.java:1288)**
	  at forge.ai.AiController.declareAttackers(AiController.java:1305)
	  at forge.ai.PlayerControllerAi.declareAttackers(PlayerControllerAi.java:653)
	  at forge.game.phase.PhaseHandler.declareAttackersTurnBasedAction(PhaseHandler.java:545)
	  at forge.game.phase.PhaseHandler.onPhaseBegin(PhaseHandler.java:322)
	  at forge.game.phase.PhaseHandler.startFirstTurn(PhaseHandler.java:1110)

The important elements here are highlighted - the AI will spend the absolute majority of time within this loop, calling other stuff as needed in order to calculate everything it needs.

So, as I suspected:
1. It's not specific to Endless Swarm, and will happen with pretty much any sufficiently filled board state (40-50+ Creature card objects on the battlefield) in the event where the AI is unable to make an immediate attack decision (assault and possibly attritional combat).
2. It's not specific to Elderscale Wurm, and will happen with any situation (created through any number of any cards) where the AI is prevented from attacking without considering the benefits and drawbacks of the said attacks on a per-card basis.

Now, I'm not sure what exactly can be done here... Maybe it needs some kind of a redesign of the entire attack/block routine, or maybe some simple targeted optimizations can be made somewhere which can make things work faster. @tool4ever , do you have any thoughts on this one? Thanks in advance!

**Comment by schnautzr** [comment]
But why does this affect my end of turn step?

**Comment by Agetian** [comment]
> But why does this affect every step where the AI has priority?

For me it doesn't do that, it only slows down in Declare Attackers. Not sure why it works that way on your end... I did increase my Java heap size to 16 GB though, so it could be helping (maybe)?

**Comment by tool4ever** [comment]
- while a few APIs try to do prediction imo it's not enough to cause that kind of slowdown with lots of **vanilla** creatures - that should be limited to combat so probably another corner case that requires further observations
- `notNeededAsBlockers` is definitely among the more expensive considerations but also one of the smarter ones, trying to balance sacrificing some intelligence for speed there might be tricky
- But the main portion of it is the loop that tries to find the sweet spot for the attackers it can spare. This currently iterates the amount linearly. For a fairly large number of attackers it might be beneficial to implement it with a binary search for quicker end result. Not a project I'd currently take on myself but as usual happy to give guidance if anyone is interested
- I suspect there are still quite a few redundant calls and the like hiding in both Attack&BlockController that can add up over time, sometimes only spottable by careful debugging and cody study. Here's just a small sample: #3422

**Comment by Agetian** [comment]
Yeah, indeed, very reasonable thoughts and considerations! Thanks for your input, @tool4ever , as well as for some clean-up! I'll take a look some more at what can be done here. Binary search is an interesting idea, definitely worth considering. I'll see if I can figure out how to do it :)

**Comment by Agetian** [comment]
I narrowed down the slowdown to this call in particular, which is done for each blocker (line 445 in AiAttackController), which runs predictive combat simulation for various attacker/blocker combinations, however, not sure what can be done to optimize this, since what it's doing appears to be reasonable and cutting down on this logic will make the predictive logic considerably less smart.

`int currentBaselineLife = ComputerUtil.predictNextCombatsRemainingLife(ai, playAggro, pilotsNonAggroDeck, 0, notNeededAsBlockers);`

There's this TODO line at ComputerUtil.java:3195 inside predictNextCombatsRemainingLife, but I'm not sure what it's referring to exactly or how to accomplish this:

`// TODO worth it to sort by creature amount for chance to terminate earlier?`

It looks like it's purely referring to the opponents' number of creatures though, and if that's correct, then it'll have no effect on 1v1 games anyway.

**Comment by Agetian** [comment]
Tested this on various Java versions and can confirm that this is much faster on Java 20 compared to Java 11 (Declare Attackers step takes around 7 sec on Java 2 on my machine vs. over 40 sec on Java 11).

**Comment by schnautzr** [comment]
Not Endless Swarm, but same issue. Here's a gamestate. Current step is the opponent's draw step. Waited at least five minutes for it to draw a card.
[state1.txt](https://github.com/Card-Forge/forge/files/11997000/state1.txt)

**Comment by Agetian** [comment]
Tested the game state above (note to self: the game saves this state incorrectly since the Prototype tokens have no link to the original and crash upon reload), the essence of the slowdown is basically the same as in the ones mentioned above - the battlefield is stalled (in this case, thanks to Elderscale Wurm and 7 life) and the battlefield is populated enough so that the complex next turn prediction run by the AI takes enough time (and yes, sadly it reruns it at every phase, when considering the outcome for the pump abilities in this case). Note that this situation isn't specific to Elderscale Wurm - even if, let's say, I added some kind of a "shortcut" for the AI to detect the Wurm + 7 life and assume it won't deal any combat damage next turn unless the situation changes, it won't stop the exact same slowdown from happening under any other circumstances, and exactly the same thing will happen if you remove Elderscale Wurm but add, let's say, 15 Wild Elephants to your side of the battlefield so that the AI can't alpha strike you. Will need to think of some more ways to optimize those routines (once again, predictNextCombatRemainingLife is a big part of it, in this case it's called through doesSpecifiedCreatureAttackAI from shouldPumpCard, which is why it happens every phase).

Interestingly, it's slow for me, but not nearly as slow as you're describing... For me, each step takes about 15 seconds or so, definitely not over 5 minutes :/ I still think that increasing the Java heap size and upgrading to a newer Java version might help you a bit with making the game more responsive, but it won't get rid of the slowdowns completely (and yes, the slowdowns will get progressively worse as the battlefield gets more and more populated).

**Comment by schnautzr** [comment]
The biggest slowdowns are happening during the opponent's upkeep, draw, and precombat main steps-- all three of these are slower than any of the combat steps. In the Slobad example, would Goblin Engineer be slowing down these three steps?

**Comment by Agetian** [comment]
No, I think it's mostly the Artificer Dragon pump abilities in the case of that particular game state (in a stalled position). Removing either the Dragons or the Wurm from the battlefield, or unstalling the board state in any other meaningful way, makes things significantly faster for me.
