### ISSUE TITLE
Bug: NPE in Quest mode

### ISSUE THREAD

**Issue by Spiggy73** [Card-Forge/forge#3653]
**Describe the bug**
Quest mode - Commander format
NPE when opponent dealt combat damage with Ichorclaw Myr
Axgard Artisan on his side, Goblin Tokens on my side (see screenshot)

**Screenshots**
![image](https://github.com/Card-Forge/forge/assets/104858028/b3f42567-f28f-4537-bdc9-c848a4631eb1)

**Desktop (please complete the following information):**
 - OS: Windows
 - Version 1.6.56

**forge.log
Game-79 > java.lang.NullPointerException
	at forge.game.trigger.TriggerCounterAddedOnce.performTest(TriggerCounterAddedOnce.java:59)
	at forge.game.trigger.TriggerHandler.canRunTrigger(TriggerHandler.java:432)
	at forge.game.trigger.TriggerHandler.runNonStaticTriggersForPlayer(TriggerHandler.java:356)
	at forge.game.trigger.TriggerHandler.runWaitingTrigger(TriggerHandler.java:335)
	at forge.game.trigger.TriggerHandler.runTrigger(TriggerHandler.java:270)
	at forge.game.player.Player.addCounterInternal(Player.java:886)
	at forge.game.GameEntityCounterTable.replaceCounterEffect(GameEntityCounterTable.java:176)
	at forge.game.GameEntityCounterTable.replaceCounterEffect(GameEntityCounterTable.java:126)
	at forge.game.GameAction.dealDamage(GameAction.java:2478)
	at forge.game.combat.Combat.dealAssignedDamage(Combat.java:940)
	at forge.game.phase.PhaseHandler.onPhaseBegin(PhaseHandler.java:356)
	at forge.game.phase.PhaseHandler.startFirstTurn(PhaseHandler.java:1110)
	at forge.game.GameAction.startGame(GameAction.java:2088)
	at forge.game.Match.startGame(Match.java:90)
	at forge.gamemodes.match.HostedMatch$2.run(HostedMatch.java:255)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)

**Comment by tool4ever** [comment]
Fixed by #3205, time to update
