### ISSUE TITLE
Another Keyword Protection error

### ISSUE THREAD

**Issue by TheLastNarwhal** [Card-Forge/forge#4525]
**Describe the bug**
It seems like Tower of the Magistrate has the same issue that Pippin had as far as protection goes, it soft locks the game.

`Game-0 > java.lang.RuntimeException: Error in Keyword Protection from artifacts for card Falkenrath Gorger
	at forge.game.keyword.KeywordInstance.createTraits(KeywordInstance.java:128)
	at forge.game.keyword.KeywordInstance.createTraits(KeywordInstance.java:86)
	at forge.game.card.Card.getKeywordForStaticAbility(Card.java:4873)
	at forge.game.card.Card.addChangedCardKeywords(Card.java:4850)
	at forge.game.ability.effects.ProtectEffect.resolve(ProtectEffect.java:156)
	at forge.game.ability.AbilityApiBased.resolve(AbilityApiBased.java:41)
	at forge.game.ability.AbilityUtils.resolveApiAbility(AbilityUtils.java:1462)
	at forge.game.ability.AbilityUtils.resolve(AbilityUtils.java:1430)
	at forge.game.zone.MagicStack.resolveStack(MagicStack.java:553)
	at forge.game.phase.PhaseHandler.startFirstTurn(PhaseHandler.java:1154)
	at forge.game.GameAction.startGame(GameAction.java:2113)
	at forge.game.Match.startGame(Match.java:90)
	at forge.gamemodes.match.HostedMatch$2.run(HostedMatch.java:255)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:840)
Caused by: java.lang.RuntimeException: unknown protection keyword: Protection from artifacts
	at forge.game.card.CardFactoryUtil.getProtectionValid(CardFactoryUtil.java:683)
	at forge.game.card.CardFactoryUtil.addReplacementEffect(CardFactoryUtil.java:2567)
	at forge.game.keyword.KeywordInstance.createTraits(KeywordInstance.java:116)
	... 15 more`

**Forge Version:** forge-gui-desktop-1.6.60-SNAPSHOT-01-15

**Comment by tool4ever** [comment]
@Hanmac 
should these just be done with Pump now instead?

**Comment by Hanmac** [comment]
@tool4ever we fixed #4456 

@TheLastNarwhal maybe you haven't uploaded yet?

**Comment by Hanmac** [comment]
> @Hanmac should these just be done with Pump now instead?

tower_of_the_magistrate van be updated with Pump because there is no Choice check
