### ISSUE TITLE
Plague of Vermin throws IllegalArgumentException when AI is low on life

### ISSUE THREAD

**Issue by jylee4** [Card-Forge/forge#5011]
**Describe the bug**
When the AI plays Plague of Vermin and its life is <= 5, it attempts to call java.util.Random.nextInt with zero as the argument which results in an IllegalArgumentException. 

**To Reproduce**
1. Here's a .pzl file you can use to Reproduce:
```

[metadata]
Name:Plague of Vermin Bug
URL:https://www.cardforge.org
Goal:Don't Crash
Turns:1
Difficulty:Easy
Description:Don't Crash
[state]
turn=1
activeplayer=p1
activephase=MAIN2
p0life=20
p0landsplayed=0
p0landsplayedlastturn=0
p0numringtemptedyou=0
p0manapool=
p0hand=Plague of Vermin|Set:SHM|Art:1
p0library=Plague of Vermin|Set:SHM|Art:1
p0graveyard=
p0battlefield=
p0exile=
p0command=
p0sideboard=
p1life=5
p1landsplayed=0
p1landsplayedlastturn=0
p1numringtemptedyou=0
p1hand=Plague of Vermin|Set:SHM|Art:1
p1library=Plague of Vermin|Set:SHM|Art:1
p1graveyard=
p1battlefield=Swamp|Set:LCI|Art:1;Swamp|Set:LCI|Art:1;Swamp|Set:LCI|Art:1;Swamp|Set:LCI|Art:1;Swamp|Set:LCI|Art:1;Swamp|Set:LCI|Art:1;Swamp|Set:LCI|Art:1
p1exile=
p1command=
p1sideboard=

```

**Expected behavior**
Well, to be honest the AI should just never play this card when it has such a low life total unless it's a winning play -- e.g. it has some kind of all rats have haste and can swing to win with just a few more. But if it does play it, then it shouldn't crash the game thread.

**Desktop (please complete the following information):**
 - OS: Win10
 - Version: GIT SNAPSHOT from main branch April 11 2024

**Comment by tehdiplomat** [comment]
@jylee4 Can you post the whole error if you have it?

**Comment by jylee4** [comment]
You mean the stack trace? Sure:
`Game-0 > java.lang.IllegalArgumentException: bound must be positive
	at java.base/java.util.Random.nextInt(Random.java:557)
	at forge.ai.AiController.chooseNumber(AiController.java:1853)
	at forge.ai.PlayerControllerAi.chooseNumber(PlayerControllerAi.java:702)
	at forge.game.ability.effects.ChooseNumberEffect.resolve(ChooseNumberEffect.java:85)
	at forge.game.spellability.AbilitySub.resolve(AbilitySub.java:105)
	at forge.game.ability.AbilityUtils.resolveApiAbility(AbilityUtils.java:1398)
	at forge.game.ability.AbilityUtils.resolve(AbilityUtils.java:1366)
	at forge.game.ability.effects.RepeatEachEffect.resolve(RepeatEachEffect.java:210)
	at forge.game.spellability.AbilitySub.resolve(AbilitySub.java:105)
	at forge.game.ability.AbilityUtils.resolveApiAbility(AbilityUtils.java:1398)
	at forge.game.ability.AbilityUtils.resolveSubAbilities(AbilityUtils.java:1382)
	at forge.game.ability.AbilityUtils.resolveApiAbility(AbilityUtils.java:1404)
	at forge.game.ability.AbilityUtils.resolve(AbilityUtils.java:1366)
	at forge.game.ability.effects.RepeatEffect.resolve(RepeatEffect.java:38)
	at forge.game.ability.SpellApiBased.resolve(SpellApiBased.java:51)
	at forge.game.ability.AbilityUtils.resolveApiAbility(AbilityUtils.java:1398)
	at forge.game.ability.AbilityUtils.resolve(AbilityUtils.java:1366)
	at forge.game.zone.MagicStack.resolveStack(MagicStack.java:582)
	at forge.game.phase.PhaseHandler.startFirstTurn(PhaseHandler.java:1126)
	at forge.game.GameAction.startGame(GameAction.java:2107)
	at forge.game.Match.startGame(Match.java:90)
	at forge.gamemodes.match.HostedMatch$2.run(HostedMatch.java:259)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1583)`

**Comment by tehdiplomat** [comment]
https://github.com/Card-Forge/forge/pull/5237
