### ISSUE TITLE
Morph spells cast by Kaervek the Punisher fail to resolve

### ISSUE THREAD

**Issue by Jetz72** [Card-Forge/forge#5048]
**Describe the bug**
Kaervek, the Punisher is one of very few cards with the effect "copy some card, you may cast the copy" (i.e. PlayEffect with `CopyCard$ True`) without either limiting the card to only Instants or Sorceries, or specifying "without paying its mana cost". Since it's not providing an alternate cost for the casting, I believe this means you should be able to use Morph and other alt costs printed on the card if all the usual requirements are met. And while you can choose this mode, and while it does end up on the stack, nothing enters the battlefield as it resolves.

Disguise causes the same issue. I don't know if other alt costs have problems. The issue can also be observed with Nashi, Moon's Legacy + Akroma, Angel of Fury. 

**To Reproduce**
Kaervek, the Punisher in battlefield; Sidisi's Pet in graveyard.
Lightning Bolt the enemy player.
Choose Sidisi's Pet for Kaervek's trigger. Affirm that you want to cast it.
Choose to cast it morphed, as a face down 2/2. Pay 3 to cast it.
Let the morphed card on the stack resolve. It does not appear in the battlefield.

**Expected behavior**
If I understand the rules correctly, the copy of the morphed card should appear in the battlefield as a face down token copy of Sidisi's Pet, able to be flipped face up. If I'm misunderstanding the rules and it should not be possible to cast a morphed creature this way, the option to do so shouldn't be presented.

**Screenshots**
![image](https://github.com/Card-Forge/forge/assets/8607832/95982f89-dff3-41e1-9b15-9d0f6c8ab889)

**Additional context**
 - Version: master at commit 4d26228ca6d28645f7be204e7bf7465758705966 (latest as of writing)
 - Rollback Experiment Enabled

**An extra oddity**
I encountered this while testing a change to PlayEffect, to apply `card.setCopiedSpell(true)` when the card is a copy made by the `CopyCard` or `CopyFromChosenName` parameters. When that's enabled, the morphed face-down copy does correctly enter the battlefield, but another problem emerges. If you click it to turn it face up, then cancel the morph cost payment, this happens when it tries to roll back:
```
Restoring game state with timestamp of :134
Game-0 > java.lang.NullPointerException: Cannot invoke "forge.game.card.Card.getId()" because the return value of "forge.game.card.Card.getCopiedPermanent()" is null
	at forge.game.GameSnapshot.copyGameState(GameSnapshot.java:368)
	at forge.game.GameSnapshot.assignGameState(GameSnapshot.java:77)
	at forge.game.GameSnapshot.restoreGameState(GameSnapshot.java:59)
	at forge.game.Game.restoreGameState(Game.java:198)
	at forge.game.GameActionUtil.rollbackAbility(GameActionUtil.java:847)
	at forge.player.HumanPlaySpellAbility.playAbility(HumanPlaySpellAbility.java:190)
	at forge.player.HumanPlay.playSpellAbility(HumanPlay.java:107)
	at forge.player.PlayerControllerHuman.playChosenSpellAbility(PlayerControllerHuman.java:1566)
	at forge.game.phase.PhaseHandler.startFirstTurn(PhaseHandler.java:1060)
	at forge.game.GameAction.startGame(GameAction.java:2107)
	at forge.game.Match.startGame(Match.java:90)
	at forge.gamemodes.match.HostedMatch$2.run(HostedMatch.java:259)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1570)
```
That could just be my fault for not having any clue what I'm doing, but it's something to keep an eye out for.

**Comment by Hanmac** [comment]
@tool4ever you probably need to check this out
