### ISSUE TITLE
Soft crash when playing Dour Port-Mage

### ISSUE THREAD

**Issue by TheLastNarwhal** [Card-Forge/forge#5650]
**Describe the bug**
When a player (human or A.I.) casts Dour Port-Mage the game soft crashes.

This is the log: 
`Game-3 > java.lang.IllegalArgumentException: No enum constant forge.game.zone.ZoneType.Ante,Command,Exile,Hand,Library
	at java.base/java.lang.Enum.valueOf(Enum.java:273)
	at forge.game.zone.ZoneType.valueOf(ZoneType.java:13)
	at forge.game.trigger.TriggerChangesZoneAll.filterCards(TriggerChangesZoneAll.java:81)
	at forge.game.trigger.TriggerChangesZoneAll.performTest(TriggerChangesZoneAll.java:55)
	at forge.game.trigger.TriggerHandler.canRunTrigger(TriggerHandler.java:435)
	at forge.game.trigger.TriggerHandler.getActiveTrigger(TriggerHandler.java:626)
	at forge.game.trigger.TriggerHandler.collectTriggerForWaiting(TriggerHandler.java:190)
	at forge.game.trigger.TriggerHandler.resetActiveTriggers(TriggerHandler.java:214)
	at forge.game.trigger.TriggerHandler.resetActiveTriggers(TriggerHandler.java:210)
	at forge.game.zone.MagicStack.removeCardFromStack(MagicStack.java:641)
	at forge.game.zone.MagicStack.finishResolving(MagicStack.java:621)
	at forge.game.zone.MagicStack.resolveStack(MagicStack.java:606)
	at forge.game.phase.PhaseHandler.startFirstTurn(PhaseHandler.java:1116)
	at forge.game.GameAction.startGame(GameAction.java:2122)
	at forge.game.Match.startGame(Match.java:90)
	at forge.gamemodes.match.HostedMatch$2.run(HostedMatch.java:274)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:840)`

**To Reproduce**
1. Cast Dour Port-Mage
2. Game crashes

**Expected behavior**
For this to not happen.

**Desktop (please complete the following information):**
 - OS: Kubuntu 22.04
 - Forge Version: forge-gui-desktop-1.6.64-SNAPSHOT-07-17

**Comment by Hanmac** [comment]
@tool4ever `Ante,Command,Exile,Hand,Library` didn't work like it thought
