### ISSUE TITLE
Crash - deck editor - Add Edit Filter > Sets...

### ISSUE THREAD

**Issue by corwin72** [Card-Forge/forge#5686]
**Describe the bug**
Filter by set causes crash in deck editor. current snapshot. Duplicated last 3 snapshots.

**To Reproduce**
1. start forge
3. go to deck editor tab
4. Click search button in upper left, next to catalog.
5. Add Edit Filter> Sets
6. Error thrown 

**Error**
Correcting zone for Yes Man, Personal Securitron (2265)
Correcting zone for Yes Man, Personal Securitron (2265)
EDT > java.lang.RuntimeException: Node FTreeNode[FTreeNodeInfo[Eternal Weekend, Eternal Weekend (PEWK)]]already present in Nodes Set (key:PEWK)
        at forge.toolbox.FCheckBoxTree.addSubtreeToCheckingStateTracking(FCheckBoxTree.java:334)
        at forge.toolbox.FCheckBoxTree.addSubtreeToCheckingStateTracking(FCheckBoxTree.java:345)
        at forge.toolbox.FCheckBoxTree.addSubtreeToCheckingStateTracking(FCheckBoxTree.java:345)
        at forge.toolbox.FCheckBoxTree.initModelCheckState(FCheckBoxTree.java:328)
        at forge.toolbox.FCheckBoxTree.setModel(FCheckBoxTree.java:208)
        at forge.toolbox.FCheckBoxTree.setTreeData(FCheckBoxTree.java:307)
        at forge.screens.home.quest.DialogChooseSets.<init>(DialogChooseSets.java:140)
        at forge.screens.home.quest.DialogChooseSets.<init>(DialogChooseSets.java:40)
        at forge.itemmanager.CardManager$4.run(CardManager.java:194)
        at forge.gui.GuiUtils$1.actionPerformed(GuiUtils.java:108)
        at javax.swing.AbstractButton.fireActionPerformed(Unknown Source)
        at javax.swing.AbstractButton$Handler.actionPerformed(Unknown Source)
        at javax.swing.DefaultButtonModel.fireActionPerformed(Unknown Source)
        at javax.swing.DefaultButtonModel.setPressed(Unknown Source)
        at javax.swing.AbstractButton.doClick(Unknown Source)
        at javax.swing.plaf.basic.BasicMenuItemUI.doClick(Unknown Source)
        at javax.swing.plaf.basic.BasicMenuItemUI$Handler.mouseReleased(Unknown Source)
        at java.awt.Component.processMouseEvent(Unknown Source)
        at javax.swing.JComponent.processMouseEvent(Unknown Source)
        at java.awt.Component.processEvent(Unknown Source)
        at java.awt.Container.processEvent(Unknown Source)
        at java.awt.Component.dispatchEventImpl(Unknown Source)
        at java.awt.Container.dispatchEventImpl(Unknown Source)
        at java.awt.Component.dispatchEvent(Unknown Source)
        at java.awt.LightweightDispatcher.retargetMouseEvent(Unknown Source)
        at java.awt.LightweightDispatcher.processMouseEvent(Unknown Source)
        at java.awt.LightweightDispatcher.dispatchEvent(Unknown Source)
        at java.awt.Container.dispatchEventImpl(Unknown Source)
        at java.awt.Window.dispatchEventImpl(Unknown Source)
        at java.awt.Component.dispatchEvent(Unknown Source)
        at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
        at java.awt.EventQueue.access$500(Unknown Source)
        at java.awt.EventQueue$3.run(Unknown Source)
        at java.awt.EventQueue$3.run(Unknown Source)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
        at java.awt.EventQueue$4.run(Unknown Source)
        at java.awt.EventQueue$4.run(Unknown Source)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
        at java.awt.EventQueue.dispatchEvent(Unknown Source)
        at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
        at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
        at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
        at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
        at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
        at java.awt.EventDispatchThread.run(Unknown Source)

**Expected behavior**
Pop up to select set for filter.

**Screenshots**

**Desktop (please complete the following information):**
Forge v.1.6.64-SNAPSHOT (forge.GuiDesktop@3a883ce7)
Windows 11 (10.0 amd64)
Java Version - 1.8.0_411
Language 'en-US' loaded successfully.

**Comment by tehdiplomat** [comment]
This error message happens if you copy over an old directory with a new build 
Try extracting to a new folder
