### ISSUE TITLE
NPE when combining certain alternative cost KW

### ISSUE THREAD

**Issue by tool4ever** [Card-Forge/forge#6064]
Case A:
- _Hunting Velociraptor_
- _Maskwood Nexus_ (so it gets Dinosaur type)
- try cast _Beloved Beggar_ disturbed

Case B:
- Defeat battle _Invasion of Ikoria_ and try cast backside (is already Dinosaur)

```
Game-2 > java.lang.RuntimeException: Error in Keyword Prowl:2 R for card Generous Soul
	at forge.game.keyword.KeywordInstance.createTraits(KeywordInstance.java:128)
	at forge.game.keyword.KeywordInstance.createTraits(KeywordInstance.java:86)
	at forge.game.card.Card.getKeywordForStaticAbility(Card.java:5130)
	at forge.game.card.Card.addChangedCardKeywords(Card.java:5107)
	at forge.game.staticability.StaticAbilityContinuous.applyContinuousAbility(StaticAbilityContinuous.java:772)
	at forge.game.staticability.StaticAbilityContinuous.applyContinuousAbility(StaticAbilityContinuous.java:72)
	at forge.game.staticability.StaticAbility.applyContinuousAbilityBefore(StaticAbility.java:238)
	at forge.game.GameAction.checkStaticAbilities(GameAction.java:1135)
	at forge.game.GameAction.checkStaticAbilities(GameAction.java:1083)
	at forge.game.GameActionUtil.addExtraKeywordCost(GameActionUtil.java:567)
	at forge.player.HumanPlaySpellAbility.playAbility(HumanPlaySpellAbility.java:117)
	at forge.player.HumanPlay.playSpellAbility(HumanPlay.java:106)
	at forge.player.PlayerControllerHuman.playChosenSpellAbility(PlayerControllerHuman.java:1509)
	at forge.game.phase.PhaseHandler.startFirstTurn(PhaseHandler.java:1055)
	at forge.game.GameAction.startGame(GameAction.java:2131)
	at forge.game.Match.startGame(Match.java:90)
	at forge.gamemodes.match.HostedMatch.lambda$1(HostedMatch.java:269)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:842)
Caused by: java.lang.NullPointerException: Cannot invoke "forge.game.spellability.SpellAbility.copyWithDefinedCost(forge.game.cost.Cost)" because the return value of "forge.game.card.CardState.getFirstSpellAbility()" is null
	at forge.game.card.CardFactoryUtil.addSpellAbility(CardFactoryUtil.java:3466)
	at forge.game.keyword.KeywordInstance.createTraits(KeywordInstance.java:117)
	... 19 more
```

the problem is these alternate states don't have a `getFirstSpellAbility()` so the Prowl KW can't use it

@Hanmac
how can we handle this?
write a helper to call instead that could lazy build a SpellPermanent?

**Comment by Hanmac** [comment]
@tool4ever we might be able to allow such a Helper

**Comment by Hanmac** [comment]
But be careful, you still can't Prowl Lands


(Maybe I need to move Prowl to the other alternative keyword costs section again?)
