### ISSUE TITLE
Any instance of tripling along with any other multiplier freezes the game.

### ISSUE THREAD

**Issue by behaigo** [Card-Forge/forge#6145]
**Describe the bug**
Whenever you have an instance of an effect that triples anything (such as City on Fire and Fiery Emancipation) as well as any other effect that multiplies the same number the game freezes and must be restarted.

**To Reproduce**
1. Start a game
2. Use debug options to play two City on Fires (though any tripling card along with any other multiplier will work)
3. Trigger the multipliers (for City on Fire simply deal damage from any source)
4. Game locks up

**Expected behavior**
What I expect to happen is a number gets tripled and then multiplied again.  For example, with two City on Fires if I use a Goblin Sharpshooter to deal damage to my opponent it should do 9 damage instead of 1 (or freezing the game)

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Version 1.6.64

**Additional context**
Using a tripling effect along with another multiplier used to work in the past.  I didn't notice this error until around version 1.6.61, though that might not be exactly when it first popped up.

**Comment by tool4ever** [comment]
Seems to work fine. Need crash log

![image](https://github.com/user-attachments/assets/aa6e203e-4faa-47c5-8f39-4c7771e8993e)

**Comment by behaigo** [comment]
Hm, my original testing was done in an online match.  I'll have to test again tomorrow, but it does indeed work as intended against the AI.

**Comment by tool4ever** [comment]
Hmn yea, that happens :(
I suspect it has something to do with the dialog to choose which replacement to apply first
@kevlahnota
can you try to debug?

**Comment by behaigo** [comment]
![Screenshot 2024-09-14 210509](https://github.com/user-attachments/assets/7c30c29d-f87a-4fdb-b5fe-499dfa803c3a)
To be a little more clear, the software doesn't crash but it gets hung up on "waiting for opponent" despite both of us acknowledging it.  I played a game against myself in two separate clients and was able to reproduce the bug.  The client doesn't crash and can still be interacted with (ex. switching tabs, working on decks, etc) but the current game in progress no longer responds.  There's two logs, I've attached both.
[forge.log](https://github.com/user-attachments/files/17004907/forge.log)
[forge0.log](https://github.com/user-attachments/files/17004908/forge0.log)

**Comment by tool4ever** [comment]
thanks. this should be it:
```
io.netty.handler.codec.EncoderException: java.io.NotSerializableException: forge.game.replacement.ReplaceDamage
	at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:125)
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717)
	at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:764)
	at io.netty.channel.AbstractChannelHandlerContext$WriteTask.run(AbstractChannelHandlerContext.java:1071)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:469)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:503)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:1623)
Caused by: java.io.NotSerializableException: forge.game.replacement.ReplaceDamage
	at java.base/java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1196)
	at java.base/java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:355)
	at java.base/java.util.ArrayList.writeObject(ArrayList.java:866)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
	at java.base/java.lang.reflect.Method.invoke(Method.java:578)
	at java.base/java.io.ObjectStreamClass.invokeWriteObject(ObjectStreamClass.java:1070)
	at java.base/java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1525)
	at java.base/java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1447)
	at java.base/java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1190)
	at java.base/java.io.ObjectOutputStream.writeArray(ObjectOutputStream.java:1390)
	at java.base/java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1186)
	at java.base/java.io.ObjectOutputStream.defaultWriteFields(ObjectOutputStream.java:1581)
	at java.base/java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1538)
	at java.base/java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1447)
	at java.base/java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1190)
	at java.base/java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:355)
	at forge.gamemodes.net.CompatibleObjectEncoder.encode(CompatibleObjectEncoder.java:25)
	at forge.gamemodes.net.CompatibleObjectEncoder.encode(CompatibleObjectEncoder.java:13)
	at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:107)
	... 10 more
```

**Comment by kevlahnota** [comment]
@tool4ever 

in playercontrollerhuman.java if you bypass the menu (getgui.one(...)) like this it will not crash but I think it really needs to be refactored and pass simple data on network maybe list of pair (index, string), get the index from selected and get the actual value using index.... seems there are multiple methods like this..

```
@Override
    public ReplacementEffect chooseSingleReplacementEffect(final List<ReplacementEffect> possibleReplacers) {
        final ReplacementEffect first = possibleReplacers.get(0);
        if (possibleReplacers.size() == 1) {
            return first;
        }
        String prompt = localizer.getMessage("lblChooseFirstApplyReplacementEffect");
        final String firstStr = first.toString();
        if (GuiBase.isNetworkplay()) //todo fix prompt for similar prompts to be serializable
            return first;
        for (int i = 1; i < possibleReplacers.size(); i++) {
            // prompt user if there are multiple different options
            if (!possibleReplacers.get(i).toString().equals(firstStr)) {
                return getGui().one(prompt, possibleReplacers);
            }
        }
        // return first option without prompting if all options are the same
        return first;
    }
```
