### ISSUE TITLE
Crash on load in Arch Linux

### ISSUE THREAD

**Issue by JLHackSeven** [Card-Forge/forge#6285]
**Describe the bug**

Crash when loading Desktop .jar version on Arch Linux

**To Reproduce**

Open forge-gui-desktop-1.6.65-SNAPSHOT-jar-with-dependencies.jar on Arch Linux

**Expected behavior**

Program loads normally

**System Info**

Name: Steam Deck
OS: SteamOS - Arch Linux

**Additional context**

App crashed, and error appeared in console

 ```
com.thoughtworks.xstream.converters.ConversionException: 
--- Debugging information
cause-exception     : java.lang.NullPointerException
cause-message       : Cannot invoke "Object.toString()" because the return value of "java.util.Map$Entry.getValue()" is null
class               : forge.deck.Deck
required-type       : forge.deck.Deck
converter-type      : com.thoughtworks.xstream.converters.reflection.ReflectionConverter
line number         : 61
class[1]            : java.util.ArrayList
required-type[1]    : java.util.ArrayList
converter-type[1]   : com.thoughtworks.xstream.converters.collections.CollectionConverter
class[2]            : forge.gamemodes.gauntlet.GauntletData
required-type[2]    : forge.gamemodes.gauntlet.GauntletData
version             : 1.6.65-SNAPSHOT
---
        at com.thoughtworks.xstream.core.TreeUnmarshaller.convert(TreeUnmarshaller.java:81)
        at com.thoughtworks.xstream.core.TreeUnmarshaller.convertAnother(TreeUnmarshaller.java:68)
        at com.thoughtworks.xstream.core.TreeUnmarshaller.convertAnother(TreeUnmarshaller.java:52)
        at com.thoughtworks.xstream.converters.collections.AbstractCollectionConverter.readBareItem(AbstractCollectionConverter.java:132)
        at com.thoughtworks.xstream.converters.collections.AbstractCollectionConverter.readItem(AbstractCollectionConverter.java:117)
        at com.thoughtworks.xstream.converters.collections.CollectionConverter.addCurrentElementToCollection(CollectionConverter.java:99)
        at com.thoughtworks.xstream.converters.collections.CollectionConverter.populateCollection(CollectionConverter.java:92)
        at com.thoughtworks.xstream.converters.collections.CollectionConverter.populateCollection(CollectionConverter.java:86)
        at com.thoughtworks.xstream.converters.collections.CollectionConverter.unmarshal(CollectionConverter.java:81)
        at com.thoughtworks.xstream.core.TreeUnmarshaller.convert(TreeUnmarshaller.java:74)
        at com.thoughtworks.xstream.core.TreeUnmarshaller.convertAnother(TreeUnmarshaller.java:68)
        at com.thoughtworks.xstream.converters.reflection.AbstractReflectionConverter.unmarshallField(AbstractReflectionConverter.java:499)
        at com.thoughtworks.xstream.converters.reflection.AbstractReflectionConverter.doUnmarshal(AbstractReflectionConverter.java:425)
        at com.thoughtworks.xstream.converters.reflection.AbstractReflectionConverter.unmarshal(AbstractReflectionConverter.java:277)
        at com.thoughtworks.xstream.core.TreeUnmarshaller.convert(TreeUnmarshaller.java:74)
        at com.thoughtworks.xstream.core.TreeUnmarshaller.convertAnother(TreeUnmarshaller.java:68)
        at com.thoughtworks.xstream.core.TreeUnmarshaller.convertAnother(TreeUnmarshaller.java:52)
        at com.thoughtworks.xstream.core.TreeUnmarshaller.start(TreeUnmarshaller.java:136)
        at com.thoughtworks.xstream.core.AbstractTreeMarshallingStrategy.unmarshal(AbstractTreeMarshallingStrategy.java:32)
        at com.thoughtworks.xstream.XStream.unmarshal(XStream.java:1421)
        at com.thoughtworks.xstream.XStream.unmarshal(XStream.java:1399)
        at com.thoughtworks.xstream.XStream.fromXML(XStream.java:1284)
        at forge.gamemodes.gauntlet.GauntletIO.loadGauntlet(GauntletIO.java:103)
        at forge.screens.home.gauntlet.CSubmenuGauntletContests.updateData(CSubmenuGauntletContests.java:64)
        at forge.screens.home.gauntlet.CSubmenuGauntletContests.initialize(CSubmenuGauntletContests.java:54)
        at forge.view.FView.initialize(FView.java:158)
        at forge.control.FControl.lambda$initialize$0(FControl.java:263)
        at java.desktop/java.awt.event.InvocationEvent.dispatch(Unknown Source)
        at java.desktop/java.awt.EventQueue.dispatchEventImpl(Unknown Source)
        at java.desktop/java.awt.EventQueue$4.run(Unknown Source)
        at java.desktop/java.awt.EventQueue$4.run(Unknown Source)
        at java.base/java.security.AccessController.doPrivileged(Unknown Source)
        at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
        at java.desktop/java.awt.EventQueue.dispatchEvent(Unknown Source)
        at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
        at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
        at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
        at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source)
        at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source)
        at java.desktop/java.awt.EventDispatchThread.run(Unknown Source)
Caused by: java.lang.NullPointerException: Cannot invoke "Object.toString()" because the return value of "java.util.Map$Entry.getValue()" is null
... 39 more
```

Full log with memory dump included, but I think the console error spells it out

There is nothing inside the /cache/gauntlet/ folder. Are there supposed to be files inside of that folder?

A zip file of anything I'm missing would help.

[hs_err_pid336718.log](https://github.com/user-attachments/files/17348289/hs_err_pid336718.log)

**Comment by weidtn** [comment]
I had the same issue and found this. Because there is no solution in here, I will post a workaround I found:

https://github.com/x-stream/xstream/issues/260#issuecomment-1367159282

> I managed to resolve it by passing these parameters:
java --illegal-access=permit --add-opens java.base/java.lang=ALL-UNNAMED --add-opens java.base/java.io=ALL-UNNAMED --add-opens java.base/java.util=ALL-UNNAMED --add-opens java.base/java.util.concurrent=ALL-UNNAMED
